version: '3.7'

services:
  mongo:
    image: mongo
    container_name: mongo
    hostname: mongo
    ports:
      - 27017:27017
    volumes:
      - /home/.docker-data/mongo:/data/db
    restart: always
    networks:
      - silentmonster.network

  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - 6379:6379
    volumes:
      - /home/.docker-data/redis:/data
    restart: always
    networks:
      - silentmonster.network

  # tor-socks:
  #   image: peterdavehello/tor-socks-proxy
  #   container_name: tor-socks
  #   ports:
  #     - 9150:9150
  #   restart: always
  #   networks: 
  #     - silentmonster.network

networks:
  silentmonster.network:
